# Generated by Django 5.0.6 on 2024-07-07 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ОЖИДАЕТ_ИСПОЛНЕНИЯ', 'PENDING'), ('В_ПРОЦЕССЕ', 'IN_PROGRESS'), ('ВЫПОЛНЕНА', 'DONE')], default='ОЖИДАЕТ_ИСПОЛНЕНИЯ', max_length=20)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_as_customer', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_as_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
