# Generated by Django 5.0.6 on 2024-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('СОТРУДНИК', 'EMPLOYEE'), ('ЗАКАЗЧИК', 'CUSTOMER')], max_length=20),
        ),
    ]
